version: "3"

services:
  ml-service:
    image: devallday/teacheck-ml-service:1.1
    environment:
      - SERVICE_PORTS=8000
    ports:
     - 8000:8000
    deploy:
      replicas: 5
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - web
  lb:
    image: dockercloud/haproxy:1.6.7
    depends_on:
      - ml-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    driver: overlay
